#ifndef ESJS_CUSTOM_LEXER_KEYWORDS_H
#define ESJS_CUSTOM_LEXER_KEYWORDS_H

#include "token.h"

// Centralized ESJS keyword inventory. Keep this list as the single source of
// truth and reuse it anywhere keyword tables are needed.
// src: https://es.js.org/sintaxis/palabras-reservadas
#define ESJS_KEYWORDS(X)                                                       \
  X("capturar")                                                                \
  X("caso")                                                                    \
  X("con")                                                                     \
  X("continuar")                                                               \
  X("crear")                                                                   \
  X("desde")                                                                   \
  X("elegir")                                                                  \
  X("esperar")                                                                 \
  X("exportar")                                                                \
  X("hacer")                                                                   \
  X("importar")                                                                \
  X("mientras")                                                                \
  X("para")                                                                    \
  X("retornar")                                                                \
  X("sino")                                                                    \
  X("si")                                                                      \
  X("constructor")                                                             \
  X("eliminar")                                                                \
  X("extiende")                                                                \
  X("finalmente")                                                              \
  X("instanciaDe")                                                             \
  X("intentar")                                                                \
  X("lanzar")                                                                  \
  X("longitud")                                                                \
  X("romper")                                                                  \
  X("simbolo")                                                                 \
  X("subcad")                                                                  \
  X("tipoDe")                                                                  \
  X("vacio")                                                                   \
  X("producir")                                                                \
  X("ambiente")                                                                \
  X("super")                                                                   \
  X("de")                                                                      \
  X("en")                                                                      \
  X("asincrono")                                                               \
  X("clase")                                                                   \
  X("const")                                                                   \
  X("var")                                                                     \
  X("mut")                                                                     \
  X("porDefecto")                                                              \
  X("funcion")                                                                 \
  X("falso")                                                                   \
  X("nulo")                                                                    \
  X("verdadero")                                                               \
  X("indefinido")                                                              \
  X("infinito")                                                                \
  X("NuN")                                                                     \
  X("ambienteGlobal")                                                          \
  X("consola")                                                                 \
  X("depurador")                                                               \
  X("establecerTemporizador")                                                  \
  X("establecerIntervalo")                                                     \
  X("Fecha")                                                                   \
  X("Numero")                                                                  \
  X("Mate")                                                                    \
  X("Matriz")                                                                  \
  X("Arreglo")                                                                 \
  X("Booleano")                                                                \
  X("Cadena")                                                                  \
  X("Funcion")                                                                 \
  X("Promesa")                                                                 \
  X("afirmar")                                                                 \
  X("limpiar")                                                                 \
  X("contar")                                                                  \
  X("reiniciarContador")                                                       \
  X("depurar")                                                                 \
  X("listar")                                                                  \
  X("listarXml")                                                               \
  X("error")                                                                   \
  X("agrupar")                                                                 \
  X("agruparColapsado")                                                        \
  X("finalizarAgrupacion")                                                     \
  X("info")                                                                    \
  X("escribir")                                                                \
  X("perfil")                                                                  \
  X("finalizarPerfil")                                                         \
  X("tabla")                                                                   \
  X("tiempo")                                                                  \
  X("finalizarTiempo")                                                         \
  X("registrarTiempo")                                                         \
  X("marcaDeTiempo")                                                           \
  X("rastrear")                                                                \
  X("adventercia")                                                             \
  X("enPosicion")                                                              \
  X("caracterEn")                                                              \
  X("codigoDeCaracterEn")                                                      \
  X("concatenar")                                                              \
  X("terminaCon")                                                              \
  X("desdeCodigoDeCaracter")                                                   \
  X("desdePuntoDeCodigo")                                                      \
  X("incluye")                                                                 \
  X("indiceDe")                                                                \
  X("ultimoIndiceDe")                                                          \
  X("compararLocalizada")                                                      \
  X("coincidir")                                                               \
  X("coindicirTodo")                                                           \
  X("normalizar")                                                              \
  X("rellenarAlFinal")                                                         \
  X("rellenarAlComienzo")                                                      \
  X("crudo")                                                                   \
  X("repetir")                                                                 \
  X("reemplazar")                                                              \
  X("reemplazarTodo")                                                          \
  X("buscarRegex")                                                             \
  X("recortar")                                                                \
  X("dividir")                                                                 \
  X("comienzaCon")                                                             \
  X("subcadena")                                                               \
  X("aMinusculasLocalizada")                                                   \
  X("AMayusculasLocalizada")                                                   \
  X("aMinuscula")                                                              \
  X("aMayuscula")                                                              \
  X("aCadena")                                                                 \
  X("recortarEspacios")                                                        \
  X("recortarEspaciosAlFinal")                                                 \
  X("recortarEspaciosAlComienzo")                                              \
  X("valorDe")                                                                 \
  X("esNuN")                                                                   \
  X("esFinito")                                                                \
  X("esEntero")                                                                \
  X("esEnteroSeguro")                                                          \
  X("interpretarDecimal")                                                      \
  X("interpretarEntero")                                                       \
  X("aExponencial")                                                            \
  X("fijarDecimales")                                                          \
  X("aCadenaLocalizada")                                                       \
  X("aPrecision")                                                              \
  X("absoluto")                                                                \
  X("arcocoseno")                                                              \
  X("arcocosenoHiperbolico")                                                   \
  X("arcoseno")                                                                \
  X("arcosenoHiperbolico")                                                     \
  X("arcotangente")                                                            \
  X("arcotangente2")                                                           \
  X("arcotangenteHiperbolica")                                                 \
  X("raizCubica")                                                              \
  X("redondearHaciaArriba")                                                    \
  X("cerosALaIzquierdaEn32Bits")                                               \
  X("coseno")                                                                  \
  X("cosenoHiperbolico")                                                       \
  X("exponencial")                                                             \
  X("exponencialMenos1")                                                       \
  X("redondearHaciaAbajo")                                                     \
  X("redondearAComaFlotante")                                                  \
  X("hipotenusa")                                                              \
  X("multiplicacionEntera")                                                    \
  X("logaritmo")                                                               \
  X("logaritmoBase10")                                                         \
  X("logaritmoDe1Mas")                                                         \
  X("logaritmoBase2")                                                          \
  X("maximo")                                                                  \
  X("minimo")                                                                  \
  X("potencia")                                                                \
  X("aleatorio")                                                               \
  X("redondear")                                                               \
  X("signo")                                                                   \
  X("seno")                                                                    \
  X("senoHiperbolico")                                                         \
  X("raizCuadrada")                                                            \
  X("tangente")                                                                \
  X("tangenteHiperbolica")                                                     \
  X("truncar")                                                                 \
  X("obtenerDia")                                                              \
  X("obtenerDiaSemana")                                                        \
  X("obtenerAnio")                                                             \
  X("obtenerAño")                                                              \
  X("obtenerHoras")                                                            \
  X("obtenerMilisegundos")                                                     \
  X("obtenerMinutos")                                                          \
  X("obtenerMes")                                                              \
  X("obtenerSegundos")                                                         \
  X("obtenerTiempo")                                                           \
  X("obtenerDesfaseDeZonaHoraria")                                             \
  X("obtenerDiaUTC")                                                           \
  X("obtenerDiaSemanaUTC")                                                     \
  X("obtenerAnioUTC")                                                          \
  X("obtenerAñoUTC")                                                           \
  X("obtenerHorasUTC")                                                         \
  X("obtenerMilisegundosUTC")                                                  \
  X("obtenerMinutosUTC")                                                       \
  X("obtenerMesUTC")                                                           \
  X("obtenerSegundosUTC")                                                      \
  X("ahora")                                                                   \
  X("analizar")                                                                \
  X("establecerFecha")                                                         \
  X("establecerAnio")                                                          \
  X("establecerAño")                                                           \
  X("establecerHoras")                                                         \
  X("establecerMilisegundos")                                                  \
  X("establecerMinutos")                                                       \
  X("establecerMes")                                                           \
  X("establecerSegundos")                                                      \
  X("establecerTiempo")                                                        \
  X("establecerFechaUTC")                                                      \
  X("establecerAnioUTC")                                                       \
  X("establecerAñoUTC")                                                        \
  X("establecerHorasUTC")                                                      \
  X("establecerMilisegundosUTC")                                               \
  X("establecerMinutosUTC")                                                    \
  X("establecerMesUTC")                                                        \
  X("establecerSegundosUTC")                                                   \
  X("aCadenaFecha")                                                            \
  X("aCadenaISO")                                                              \
  X("aJSON")                                                                   \
  X("aCadenaFechaLocale")                                                      \
  X("aCadenaLocale")                                                           \
  X("aCadenaTiempoLocale")                                                     \
  X("aCadenaTiempo")                                                           \
  X("aCadenaUTC")                                                              \
  X("UTC")                                                                     \
  X("posicion")                                                                \
  X("copiarDentro")                                                            \
  X("entradas")                                                                \
  X("cada")                                                                    \
  X("llenar")                                                                  \
  X("filtrar")                                                                 \
  X("buscar")                                                                  \
  X("buscarIndice")                                                            \
  X("buscarUltimo")                                                            \
  X("buscarUltimoIndice")                                                      \
  X("plano")                                                                   \
  X("planoMapear")                                                             \
  X("paraCada")                                                                \
  X("grupo")                                                                   \
  X("grupoAMapear")                                                            \
  X("mapear")                                                                  \
  X("sacar")                                                                   \
  X("agregar")                                                                 \
  X("reducir")                                                                 \
  X("reducirDerecha")                                                          \
  X("reverso")                                                                 \
  X("sacarPrimero")                                                            \
  X("rodaja")                                                                  \
  X("algun")                                                                   \
  X("ordenar")                                                                 \
  X("empalmar")                                                                \
  X("agregarInicio")                                                           \
  X("valores")                                                                 \
  X("todos")                                                                   \
  X("todosTerminados")                                                         \
  X("cualquiera")                                                              \
  X("carrera")                                                                 \
  X("rechaza")                                                                 \
  X("resuelve")                                                                \
  X("luego")                                                                   \
  X("esNulo")

/**
 * @brief Looks up a reserved word or literal keyword by lexeme.
 *
 * @param lexeme Input lexeme.
 * @param length Lexeme length in bytes.
 * @return TokenType Specific keyword token type, or TOKEN_IDENTIFIER when the
 * lexeme is not reserved.
 */
TokenType keyword_lookup(const char *lexeme, size_t length);

#endif // ESJS_CUSTOM_LEXER_KEYWORDS_H